Добавил Entity,VO для Id.Изменил конфиг DbContext
kirill-vatutin/PetFamily pull request #7
Opened 2024-08-18 19:37 UTC by kirill-vatutin

Добавил базовую Entity,ValueObject для Id сущностей. Отредачил конфигурации, применил миграции и обновил бд

2024-08-18 22:00 UTC, Asasen1 requested changes
Социальные сети и реквизиты должны быть списком.
Также сделай у волонтёра кол-во животных методом.
Пример:
public int PetsLookingForHome() => _pets.Count(p => p.HelpStatus == HelpStatus.LookingForHome);

2024-08-18 22:00 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
>          public FIO Fio { get; private set; } = null!;
Не используй сокращения, тем более на русском. Напиши например FullName

2024-08-18 22:00 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Modules/Volunteer.cs
> +            var volunteer = new Volunteer(id,fio, description, yearsExperience, phoneNumber, requisite);
Можешь просто вернуть волонтёра

2024-08-19 10:28 UTC, KirillSachkov requested changes

2024-08-19 10:28 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            builder.OwnsMany(p => p.Requisites, pb =>
Так не будет работать. Теперь нужно сделать обёртку над реквезитами и написать OwnsOne, и внутри уже указать ToJson и OwnsMany с реквизитами, тоже самое и с фотками

2024-08-19 10:36 UTC, kirill-vatutin commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            builder.OwnsMany(p => p.Requisites, pb =>
@KirillSachkov  я правильно понимаю, что должно быть так, как в первом коммите? есть список фото, есть рекорд обертка для него и конфигурируется именно обертка с вложенным списком

2024-08-19 10:40 UTC, KirillSachkov commented on backend/src/PetFamily.Infrastructure/Configuration/PetConfiguration.cs
> +            builder.OwnsMany(p => p.Requisites, pb =>
да

2024-08-19 19:49 UTC, YADARAN1 approved these changes

2024-08-19 20:01 UTC, merged